window.EP_DATA = {
  years: [
    { id: "2024-2025", label: "24·25", status: "archive" },
    { id: "2025-2026", label: "25·26", status: "archive-pending" },
    { id: "2026-2027", label: "26·27", status: "current" },
    { id: "2027-2028", label: "27·28", status: "future" },
  ],
  currentYear: "2026-2027",

  projects: [
    {
      id: "animal-crossing", num: 1,
      slug: "animal-crossing-reengineering-effective-wildlife-crossing-structures-at-the-jamestown-dam",
      title: "Animal Crossing: Reengineering Effective Wildlife Crossing Structures At The Jamestown Dam",
      advisor: "Randy Chambers", affiliation: "ENSP", advisorEmail: "rmcham@wm.edu",
      coadvisors: "Ran Yang, Physics",
      areas: ["Instrumentation / sensors", "Public-facing / installation / outreach"],
      pitch: "There are thousands of small dams that impound water across the Virginia coastal plain, but the dams impede the migrations of fishes and other organisms. Students will work with Keck Lab personnel to design, install, and monitor equipment to facilitate upstream movements of migratory animals, thereby opening habitats underutilized owing to the dams.",
      background: "Water flows downhill, but migratory organisms flow upstream to complete their life cycles. Dams effectively break the cycles. Because dam removal currently is not an option, the problem must be addressed another way. The animal team plans to work on engineering potential pathways to facilitate the flow of organisms like fish over dams. Starting with research and review of past methodologies (e.g., fish ladders, salmon guns), the team will target a species, identify the specific barriers to upstream migration posed by the Lake Matoaka dam on Jamestown Road, then engineer a structure that could assist with migration. The team would hope to demonstrate the effectiveness of their engineering solution via in-stream videography of successful animal migrations at the dam.",
      workspace: "The team will work in Physics (Yang lab) and in the Keck Environmental Lab and in the field (Lake Matoaka and College Creek).",
      notes: "I've never been involved in EPAD projects before, so this is all new to me!",
    },
    {
      id: "usv-race-boat", num: 2,
      slug: "modification-of-a-high-speed-electric-unmanned-surface-vessel-usv-race-boat-towards-full-stack-agentic-control",
      title: "Modification of a high-speed, electric, unmanned surface vessel (USV) race boat towards full-stack agentic control.",
      advisor: "Jonathan Frey", affiliation: "Applied Science", advisorEmail: "jfrey@wm.edu",
      coadvisors: null,
      areas: ["AI-driven measurement or analysis", "Robotics / autonomy / controls", "Public-facing / installation / outreach", "Instrumentation / sensors"],
      pitch: "William & Mary Racing is moving to improve the mechanical systems of the unmanned race boat to achieve higher average speeds as well as modifying the autonomous control systems and sensors to achieve full stack agentic AI control of the vessel.",
      background: "The team will be focused on competing in the ASNE collegiate race in April within the autonomous race division. This project will result in delivered and tested hardware and electronics as well as software and firmware developed within the stack. We are working to turn the W&M racing vessel, Pesce Volante, into an autonomous vessel akin to Kit from the tv show Knight Rider.",
      workspace: "Makerspace",
      notes: null,
    },
    {
      id: "photosensor-readout", num: 3,
      slug: "photosensor-readout-electronics-for-fun-and-profit",
      title: "Photosensor readout electronics for fun and profit*",
      advisor: "Mike Kordosky", affiliation: "Physics", advisorEmail: "makordosky@wm.edu",
      coadvisors: null,
      areas: ["Bioengineering / medical devices", "Instrumentation / sensors", "Plasma / high-energy adjacent"],
      pitch: "If you've wondered how the analog signals that come out of sensors end up as numbers on a computer this project is for you. You'll build the so-called front-end readout for photodetectors that are sensitive to single photons with a time resolution of a few ns. Pick this project if you like electronics and instrumentation and want a challenge combining hardware and software.",
      background: "Photosensors with single photon and few ns resolution are widely used in high-energy and nuclear physics as well as in adjacent fields like medical physics. They are typically read out with bespoke hardware that takes delta-function like current pulses from the sensor, shapes and amplifies them (in the RC-CR sense) and then digitizes them to produce numbers. The digitizer and front end usually service multiple inputs and are controlled and read-out by a micro-controller (ex: arduino). The goal of this project is to design, construct, and characterize a readout system consisting of one or more PCBs.",
      workspace: "Work will be done in our labs in the Small Hall research wing.",
      notes: "This project needs a team with members who liked analog electronics (PHYS 252) and were decent at it. It would also benefit from having some members who have taken instrumentation (PHYS 351) or who are planning to take it in F26. Team members will also need some programming experience (via PHYS 256 or similar) and will benefit from experience with linux/unix.",
    },
    {
      id: "irays-pupillometry", num: 4,
      slug: "irays-computational-dual-spectrum-pupillometry-for-pre-hospital-neuro-triage",
      title: "iRays: Computational Dual-Spectrum Pupillometry for Pre-Hospital Neuro-Triage",
      advisor: "Ran Yang", affiliation: "Physics", advisorEmail: "rxyan2@wm.edu",
      coadvisors: "Gunter Luepke, Applied Science",
      areas: ["Instrumentation / sensors", "AI-driven measurement or analysis", "Bioengineering / medical devices", "Computational imaging / simulation", "Robotics / autonomy / controls"],
      pitch: "You are a year away from being engineers, not students, and iRays is the rare project where the distance between a William & Mary lab bench and the back of an ambulance and emergencies is exactly as far as you carry it; most undergraduates leave school without ever feeling that line disappear. Across the year you will get hands on with computational imaging, on-device AI, PCB and firmware integration, and the discipline of designing for a user who has 90 seconds and one free hand. This is not a \"might someday be useful\" project; it is an NIH-funded industry problem with active IRB approval, a filed patent, and a fire department waiting on the device. The pupils you teach this unit to read belong to people having strokes, overdoses, and head injuries, and faster, objective answers in those minutes save lives.",
      background: "Acute brain emergencies (stroke, traumatic brain injury, overdose) make up a large share of 911 calls, but the only neurologic tool in most ambulances is a penlight check that is subjective, hard to document, and wrong up to 66 percent of the time. iRays replaces that penlight with a handheld dual-spectrum imager that captures the pupillary light reflex (PLR), the fastest direct bedside indicator of brain function, and runs on-device AI to extract size, latency, constriction velocity, and binocular asymmetry in seconds. The physics core is computational imaging under uncontrolled motion: timed visible and infrared illumination, contact-free geometry correction (the \"Star Ruler\" depth model), event-synchronized stimulus timing (the \"Pink Frame\" method), and segmentation models that must run real time on edge compute.\nThe capstone team will own one integration thread that turns the existing benchtop prototype into a field-testable unit. Concretely, the team will (1) build and characterize a synthetic-eye replay rig for repeatable, ground-truth bench validation; (2) integrate dual-spectrum illumination and binocular acquisition into a handheld enclosure; (3) execute a structured measurement campaign on the rig covering timing accuracy, depth correction, and PLR feature repeatability under scripted motion and more.\nYear-end deliverables: a working handheld prototype, a calibrated synthetic-eye test bench, a characterized dataset with quantitative repeatability metrics, a live April Showcase demo, and a publication-ready technical report. Strong students will be positioned to co-author a peer-reviewed paper and contribute to follow-on patent disclosures.",
      workspace: "Primary workspace: Dr. Yang's Point of Care Lab in William & Mary Physics (Small Hall 234) for integration, embedded build-out, and bench measurement. Optical characterization and eye safety verification will occur in Dr. Luepke's lab in Small Hall. Day-to-day human subjects activities under the iRays IRB and IDE are handled by the graduate engineer and the Hampton Fire & Rescue partner team, so the capstone scope is primarily bench based on synthetic eyes. If a project thread benefits from limited human subjects involvement, the undergraduate team will complete CITI human subjects training and be added to the IRB protocol.",
      notes: null,
    },
    {
      id: "audimo", num: 5,
      slug: "audimo-sensor-augmented-acoustic-instruments",
      title: "Audimo (Sensor-Augmented Acoustic Instruments)",
      advisor: "Benjamin D. Whiting", affiliation: "Music", advisorEmail: "bdwhiting@wm.edu",
      coadvisors: "Ran Yang, Physics; Melody Chua, Kunst Universität Graz (KUG)",
      areas: ["Instrumentation / sensors"],
      pitch: "Audimo aims to deliver tighter integration of acoustic instruments into electronic music performance and improvisation. Eschewing uncomfortable solutions like stomp boxes and bulky sensor attachments that require the performer to move in ways that are unidiomatic to their instrument, it will allow performers the ability to control electronic effects and synthesized or sampled audio in a way that jives with how they normally play.",
      background: "This project builds upon the progress made by current seniors Jennifer Tsai and Felix Iov during the 2025AY. Audimo currently exists as an alpha-state prototype. It is compact, sports a 9-axis motion sensor and proximity sensor for gesture recognition, as well as a small microphone for amplitude and pitch tracking. It operates by taking the data logged on the SBC (currently a Raspberry Pi Pico), bundling the values into Open Sound Control (OSC)-formatted messages, and then transmitting those messages to the Audimo DAW plugin on the host computer. The user then has the option to either use one of the several audio FX processes in the plugin or transmit the values to another destination (e.g., another plugin in the DAW or to an external audio programming platform like Pure Data or Max/MSP).\n\nWhile it is already a capable device in its own right, there is still much to accomplish for Audimo to realize its purpose as a sensor augmentation for any instrument, including those that are typically stationary when played. This matters as there exists a number of practitioners of contemporary electronic and electroacoustic music composition, improvisation, and performance who are eager for such a solution that current commercially available offerings (namely, MUGIC Motion) either do not adequately address or are incompatible with their instrument or manner of performance. What Audimo aims to offer is a degree of flexibility heretofore unprecedented in this area.\n\nKey deliverables by the end of the 2026AY include the following:\n• Incorporation of microcontrollers and other components to replace the RPi Pico\n• Refinement of dynamic time warping algorithm for improved gesture recognition accuracy\n• Adoption of a more robust proximity sensing solution as well as others that will assist in measuring performance data from stationary instruments\n• Improvement of form factor and instrument mounting solutions\n• UI/UX improvements for the plugin, as well as the incorporation of more audio effects\n• Development of presets for instruments to aid in calibration and parameter mapping\n• Demo of beta-state prototype at the April Showcase, as well as (ideally) a publication-ready report",
      workspace: "Weekly meetings will occur in the Experimental Project Studio (room 062) in the basement of the Music Arts Center. Pending approval, hardware work will continue to be conducted in Ran's Lab in Small Hall. Testing sessions with volunteer musicians will be conducted in the Music Arts Center, either in the Experimental Project Studio (MAC 062) or the Vlahakis Recording Studio (MAC 064) depending on the nature of the test. Testing of the sound quality of the plugin can be conducted in the new Sound Design Studio (MAC 065) over stereo studio monitors in an acoustically treated space, or in the Experimental Project Studio for testing over a 6.1 surround sound system.",
      notes: "The team will, on occasion, meet remotely with other experts in the field of sensor-augmented instruments and AI-powered improvisation machines for guidance. My team had a lot of fun this year getting this initiative started, and I expect next year will prove to be just as, if not even more, exhilarating and rewarding.",
    },
    {
      id: "smr-heat-load", num: 6,
      slug: "developing-heat-load-model-and-solutions-for-smr-located-on-former-mining-site",
      title: "Developing heat load model and solutions for SMR located on former mining site",
      advisor: "Saskia Mordijck", affiliation: "Physics", advisorEmail: "smordijck@wm.edu",
      coadvisors: null,
      areas: ["Computational imaging / simulation"],
      pitch: "Most conflicts in the world can reduced to 3 topics: Water, Energy & data. In this project, you will directly be able to contribute to real world challenge through assessing the ability of a former mining site to provide the cooling for small modular reactors.",
      background: "This project will involve assessing the heat capacity of mine water in combination with an artificial open air basin for supporting Small Modular Reactors in Southwest Virginia. Students will have to develop an increasingly complex system using open source software such as TESPy (a thermal engineering software package for energy systems). The students will have to develop a solution which includes multiple heat deposits, addresses environmental temperatures, realistic pumps and water flow rates for a variety of environmental conditions. In addition, advanced modeling of the mine using open source software MODFLOW can address the impact of multi year operation and localized temperatures in the mine itself.",
      workspace: "This work requires computers and internet access.",
      notes: "This project will put you in contact with major energy companies and engage with a former W&M alumnus.",
    },
    {
      id: "soft-bio-robot", num: 7,
      slug: "soft-shallow-water-biomimetic-robot",
      title: "Soft Shallow Water Biomimetic Robot",
      advisor: "Jonathan Frey", affiliation: "Applied Science", advisorEmail: "jfrey@wm.edu",
      coadvisors: null,
      areas: ["Public-facing / installation / outreach", "Instrumentation / sensors", "Robotics / autonomy / controls"],
      pitch: "Marine ecosystems represent a vastly complex and diverse area of study that pose accessibility challenges for direct human interaction. Such regions have traditionally been studied by underwater autonomous vehicles utilizing propeller-based locomotion. However, these are limited in their maneuverability, speed, and natural integration. Soft robotics represent a viable alternative to efficiently navigate sensitive marine ecosystems with minimal disturbance. Using biomimetics as design framework, this project will work towards developing a soft remotely operated underwater vehicle in the form factor of a manta ray for use in observation of shallow water marine environments with minimal disturbance.",
      background: "This project will result in a remotely operated soft robotic manta ray.",
      workspace: "Makerspace",
      notes: null,
    },
    {
      id: "biofilm-corrosion", num: 8,
      slug: "corrosion-prevention-using-engineered-biofilms",
      title: "Corrosion Prevention Using Engineered Biofilms",
      advisor: "Margaret Saha", affiliation: "Applied Science", advisorEmail: "mssaha@wm.edu",
      coadvisors: "Doug Beringer; Dennis Manos",
      areas: ["Bioengineering / medical devices", "Instrumentation / sensors", "Materials"],
      pitch: "Developing novel approaches using biofilms to prevent corrosion is important because traditional anti-corrosion methods often rely on toxic chemicals that can harm the environment. Corrosion causes an estimated $2.5 trillion in damage globally each year, or about 3–4% of global GDP, making more effective solutions economically critical. Biofilms offer a more sustainable and potentially self-regenerating solution by forming protective layers on material surfaces. They can adapt to changing conditions, improving long-term durability, reducing maintenance costs, and helping mitigate the massive economic burden of corrosion.",
      background: "By the end of the year, the team expects to produce several concrete artifacts, including a characterized dataset on biofilm performance under different environmental conditions and a validated experimental setup for testing corrosion resistance. This will include the development of a flow chamber that mimics real-world water movement experienced by ships and bridges, enabling more realistic testing conditions. The team also aims to create a prototype or proof-of-concept demonstrating biofilm-based protection on a material sample. Additionally, the project should result in a publication-ready report and a live or recorded demonstration suitable for presentation at the April Showcase.",
      workspace: "Team will work in ISC4 — in several labs and Core Labs.",
      notes: "The bacteria producing the biofilm is BSL1 — same safety level as the bacteria in the yogurt one eats for breakfast!",
    },
    {
      id: "quantum-forge", num: 9,
      slug: "quantum-forge-pilot-project-with-inq-in-quantum-computing-or-quantum-sensing",
      title: "Quantum Forge Pilot Project with INQ in Quantum Computing or Quantum Sensing",
      advisor: "INQ Industry Mentor", affiliation: "Industry / Quantum Forge", advisorEmail: null,
      coadvisors: "A William & Mary Physics professor in quantum computing or quantum sensing (TBD)",
      areas: ["Quantum science and technology", "Computational imaging / simulation", "Instrumentation / sensors"],
      pitch: "Quantum is no longer just basic science. It is now an applied, engineering-driven field where teams build devices, control systems, algorithms, and measurement platforms that matter outside the lab. This proposed Quantum Forge capstone with INQ puts students inside that shift. You would join a year-long project in either quantum computing or quantum sensing, work directly with a quantum industry technical lead, and help shape solutions to a real problem emerging from the quantum technology sector.",
      background: "This proposed capstone project is part of Quantum Forge, a year-long capstone model developed by NSF Q-SEnSE to engage undergraduate students in real-world quantum information science and technology projects. For the 2026-2027 William & Mary Engineering Physics capstone cohort, this project is being developed with INQ as a pilot industry collaboration. INQ works in areas connected to quantum computing and quantum sensing, and the final project scope is now being defined in conversation with the company and program mentors.\n\nThe project is expected to fall in one of two applied directions: quantum computing or quantum sensing. Students will be working in a part of quantum technology that increasingly looks like modern engineering: defining requirements, comparing architectures, modeling system behavior, evaluating hardware or software constraints, building and testing workflows, and communicating results to technical stakeholders.\n\nStudents who choose this project will be directly mentored by an INQ quantum industry technical lead together with Quantum Forge or Q-SEnSE affiliated mentorship and a William & Mary Physics co-advisor. Deliverables include a technical background review, a clearly defined problem statement with requirements, intermediate design or progress reviews, and a final report and presentation.",
      workspace: "Primary work will be based in William & Mary Physics and associated engineering spaces, with regular interaction with external mentors. Specific laboratory, computational, or instrumentation access will depend on whether the final project centers on quantum computing or quantum sensing.",
      notes: "This is a proposed pilot Quantum Forge project for the 2026-2027 capstone cycle. The exact topic is still being finalized with INQ and program mentors.",
    },
  ],

  // Sample student responses — drives the dashboard demo
  responses: [
    { name: "Aiyana Patel",   email: "appatel@wm.edu",     ranking: ["irays-pupillometry","quantum-forge","photosensor-readout","audimo","usv-race-boat","biofilm-corrosion","soft-bio-robot","smr-heat-load","animal-crossing"], notes: "ML/CV interest" },
    { name: "Bennett Cho",    email: "bcho@wm.edu",        ranking: ["usv-race-boat","soft-bio-robot","irays-pupillometry","photosensor-readout","quantum-forge","animal-crossing","smr-heat-load","biofilm-corrosion","audimo"], notes: "Loves robotics" },
    { name: "Cara Lin",       email: "clin@wm.edu",        ranking: ["quantum-forge","photosensor-readout","smr-heat-load","irays-pupillometry","biofilm-corrosion","audimo","usv-race-boat","soft-bio-robot","animal-crossing"], notes: "Theory-leaning" },
    { name: "Daniel Reyes",   email: "dreyes@wm.edu",      ranking: ["irays-pupillometry","photosensor-readout","quantum-forge","biofilm-corrosion","audimo","usv-race-boat","soft-bio-robot","smr-heat-load","animal-crossing"], notes: "Pre-med + EE" },
    { name: "Elena Rosario",  email: "erosario@wm.edu",    ranking: ["audimo","irays-pupillometry","biofilm-corrosion","photosensor-readout","quantum-forge","soft-bio-robot","usv-race-boat","animal-crossing","smr-heat-load"], notes: "Cellist" },
    { name: "Felix Okafor",   email: "fokafor@wm.edu",     ranking: ["usv-race-boat","soft-bio-robot","animal-crossing","irays-pupillometry","photosensor-readout","biofilm-corrosion","quantum-forge","smr-heat-load","audimo"], notes: "Wants outdoor + robotics" },
    { name: "Gita Mehta",     email: "gmehta@wm.edu",      ranking: ["biofilm-corrosion","irays-pupillometry","photosensor-readout","quantum-forge","soft-bio-robot","audimo","animal-crossing","usv-race-boat","smr-heat-load"], notes: "Bio + materials" },
    { name: "Henrik Sato",    email: "hsato@wm.edu",       ranking: ["smr-heat-load","quantum-forge","photosensor-readout","irays-pupillometry","usv-race-boat","biofilm-corrosion","soft-bio-robot","animal-crossing","audimo"], notes: "Sim-heavy" },
    { name: "Isla Berger",    email: "iberger@wm.edu",     ranking: ["animal-crossing","soft-bio-robot","biofilm-corrosion","usv-race-boat","irays-pupillometry","photosensor-readout","audimo","quantum-forge","smr-heat-load"], notes: "ENSP minor" },
    { name: "Jasper Kim",     email: "jkim@wm.edu",        ranking: ["irays-pupillometry","quantum-forge","photosensor-readout","biofilm-corrosion","usv-race-boat","soft-bio-robot","smr-heat-load","audimo","animal-crossing"], notes: "MD-PhD aspirant" },
    { name: "Kalia Brooks",   email: "kbrooks@wm.edu",     ranking: ["audimo","animal-crossing","soft-bio-robot","irays-pupillometry","biofilm-corrosion","photosensor-readout","quantum-forge","usv-race-boat","smr-heat-load"], notes: "Music + outreach" },
    { name: "Liam Donnelly",  email: "ldonnelly@wm.edu",   ranking: ["usv-race-boat","photosensor-readout","quantum-forge","irays-pupillometry","soft-bio-robot","smr-heat-load","biofilm-corrosion","animal-crossing","audimo"], notes: "Embedded systems" },
    { name: "Maya Underwood", email: "munderwood@wm.edu",  ranking: ["quantum-forge","smr-heat-load","photosensor-readout","irays-pupillometry","usv-race-boat","biofilm-corrosion","soft-bio-robot","audimo","animal-crossing"], notes: "Industry-curious" },
    { name: "Nikhil Verma",   email: "nverma@wm.edu",      ranking: ["soft-bio-robot","usv-race-boat","irays-pupillometry","animal-crossing","photosensor-readout","biofilm-corrosion","quantum-forge","audimo","smr-heat-load"], notes: "Soft robotics" },
    { name: "Owen Park",      email: "opark@wm.edu",       ranking: ["photosensor-readout","irays-pupillometry","quantum-forge","biofilm-corrosion","smr-heat-load","usv-race-boat","soft-bio-robot","audimo","animal-crossing"], notes: "Detector electronics" },
    { name: "Priya Anand",    email: "panand@wm.edu",      ranking: ["biofilm-corrosion","animal-crossing","irays-pupillometry","audimo","photosensor-readout","soft-bio-robot","usv-race-boat","quantum-forge","smr-heat-load"], notes: "Wet-lab fluent" },
    { name: "Quinn Hall",     email: "qhall@wm.edu",       ranking: ["irays-pupillometry","audimo","photosensor-readout","biofilm-corrosion","quantum-forge","usv-race-boat","soft-bio-robot","animal-crossing","smr-heat-load"], notes: "" },
    { name: "Rohan Iyer",     email: "riyer@wm.edu",       ranking: ["quantum-forge","irays-pupillometry","photosensor-readout","smr-heat-load","biofilm-corrosion","audimo","usv-race-boat","soft-bio-robot","animal-crossing"], notes: "Quantum-curious" },
    { name: "Sam Whitaker",   email: "swhitaker@wm.edu",   ranking: ["usv-race-boat","photosensor-readout","irays-pupillometry","soft-bio-robot","quantum-forge","biofilm-corrosion","smr-heat-load","audimo","animal-crossing"], notes: "" },
    { name: "Talia Greene",   email: "tgreene@wm.edu",     ranking: ["irays-pupillometry","biofilm-corrosion","audimo","photosensor-readout","animal-crossing","quantum-forge","soft-bio-robot","usv-race-boat","smr-heat-load"], notes: "Pre-med" },
    { name: "Uma Castillo",   email: "ucastillo@wm.edu",   ranking: ["soft-bio-robot","animal-crossing","biofilm-corrosion","usv-race-boat","irays-pupillometry","photosensor-readout","audimo","smr-heat-load","quantum-forge"], notes: "Field bio" },
    { name: "Victor Ng",      email: "vng@wm.edu",         ranking: ["photosensor-readout","quantum-forge","smr-heat-load","irays-pupillometry","biofilm-corrosion","usv-race-boat","soft-bio-robot","audimo","animal-crossing"], notes: "Detector + sim" },
  ],

  archive: [
    { year: "2024-2025", title: "Founding cohort", projects: 7, teams: 3, students: 9, summary: "First Engineering Physics capstone year. Hand-matched teams, shared lab space established at Small Hall.", status: "past" },
    { year: "2025-2026", title: "Second cohort", projects: 8, teams: 3, students: 8, summary: "Introduced industry partner mentorship pilots. Public showcase added at the Sadler Center.", status: "past" },
    { year: "2026-2027", title: "Current cohort — you are here", projects: 9, teams: null, students: 22, summary: "Ranking poll + first auto team-making preview running this year. Quantum Forge industry track joins the slate.", status: "current" },
    { year: "2027-2028", title: "Reserved", projects: null, teams: null, students: null, summary: "Placeholder for next year. Ranking and team data will land here once the cohort starts.", status: "future" },
  ],
};
